<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Yaf Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="/css/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="/images/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" >
    <!-- Scripts -->
    <script type="text/javascript" src="/js/jquery.min.js"></script>
<!--[if lt IE 9]> <script type="text/javascript" src="/js/html5.js"></script><![endif]-->
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Yaf Application</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      {block name=content}{/block}

      <hr>
      <footer>
        <p>&copy; 2012 by Jlake Ou. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
